services:
  postgres:
    image: postgres:18
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: koheroke
      POSTGRES_PASSWORD: azumax1000
      POSTGRES_DB: app
    volumes:
        - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
  

