services:
  postgres:
    image: postgres:18
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: motinabi_db_user
      POSTGRES_PASSWORD: fahITs2vs54SzHirNDOfAn9zAzEXTFs6
      POSTGRES_DB: app
    volumes:
        - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
  

